package net.cafestube.wiretapper.entity;

import java.lang.reflect.Field;

/**
 * This class is auto-generated by EntityDataAccessorsCodegen.
 * Do not modify this file directly. Instead, modify and run the codegen tool.
 * <p>
 * Generated Entity Data Accessors for Minecraft version: 1.21.10
 */
@SuppressWarnings("unused")
public final class EntityDataAccessors {

    @SuppressWarnings("unchecked")
    private static <T> T resolve(Class<?> owner, String fieldName) {
        try {
            Field f = owner.getDeclaredField(fieldName);
            f.setAccessible(true);
            return (T) f.get(null);
        } catch (Throwable t) {
            System.err.println("Warning: failed to resolve '" + owner.getName() + "." + "' -> " + t);
            return null;
        }
    }

    public static class Entity {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Byte> DATA_SHARED_FLAGS_ID = resolve(net.minecraft.world.entity.Entity.class, "DATA_SHARED_FLAGS_ID");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Integer> DATA_AIR_SUPPLY_ID = resolve(net.minecraft.world.entity.Entity.class, "DATA_AIR_SUPPLY_ID");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.util.Optional<net.minecraft.network.chat.Component>> DATA_CUSTOM_NAME = resolve(net.minecraft.world.entity.Entity.class, "DATA_CUSTOM_NAME");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Boolean> DATA_CUSTOM_NAME_VISIBLE = resolve(net.minecraft.world.entity.Entity.class, "DATA_CUSTOM_NAME_VISIBLE");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Boolean> DATA_SILENT = resolve(net.minecraft.world.entity.Entity.class, "DATA_SILENT");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Boolean> DATA_NO_GRAVITY = resolve(net.minecraft.world.entity.Entity.class, "DATA_NO_GRAVITY");
        public static final net.minecraft.network.syncher.EntityDataAccessor<net.minecraft.world.entity.Pose> DATA_POSE = resolve(net.minecraft.world.entity.Entity.class, "DATA_POSE");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Integer> DATA_TICKS_FROZEN = resolve(net.minecraft.world.entity.Entity.class, "DATA_TICKS_FROZEN");
    }


    public static class AreaEffectCloud extends Entity {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Float> DATA_RADIUS = resolve(net.minecraft.world.entity.AreaEffectCloud.class, "DATA_RADIUS");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Boolean> DATA_WAITING = resolve(net.minecraft.world.entity.AreaEffectCloud.class, "DATA_WAITING");
        public static final net.minecraft.network.syncher.EntityDataAccessor<net.minecraft.core.particles.ParticleOptions> DATA_PARTICLE = resolve(net.minecraft.world.entity.AreaEffectCloud.class, "DATA_PARTICLE");
    }

    public static class Display extends Entity {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Integer> DATA_TRANSFORMATION_INTERPOLATION_START_DELTA_TICKS_ID = resolve(net.minecraft.world.entity.Display.class, "DATA_TRANSFORMATION_INTERPOLATION_START_DELTA_TICKS_ID");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Integer> DATA_TRANSFORMATION_INTERPOLATION_DURATION_ID = resolve(net.minecraft.world.entity.Display.class, "DATA_TRANSFORMATION_INTERPOLATION_DURATION_ID");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Integer> DATA_POS_ROT_INTERPOLATION_DURATION_ID = resolve(net.minecraft.world.entity.Display.class, "DATA_POS_ROT_INTERPOLATION_DURATION_ID");
        public static final net.minecraft.network.syncher.EntityDataAccessor<org.joml.Vector3f> DATA_TRANSLATION_ID = resolve(net.minecraft.world.entity.Display.class, "DATA_TRANSLATION_ID");
        public static final net.minecraft.network.syncher.EntityDataAccessor<org.joml.Vector3f> DATA_SCALE_ID = resolve(net.minecraft.world.entity.Display.class, "DATA_SCALE_ID");
        public static final net.minecraft.network.syncher.EntityDataAccessor<org.joml.Quaternionf> DATA_LEFT_ROTATION_ID = resolve(net.minecraft.world.entity.Display.class, "DATA_LEFT_ROTATION_ID");
        public static final net.minecraft.network.syncher.EntityDataAccessor<org.joml.Quaternionf> DATA_RIGHT_ROTATION_ID = resolve(net.minecraft.world.entity.Display.class, "DATA_RIGHT_ROTATION_ID");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Byte> DATA_BILLBOARD_RENDER_CONSTRAINTS_ID = resolve(net.minecraft.world.entity.Display.class, "DATA_BILLBOARD_RENDER_CONSTRAINTS_ID");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Integer> DATA_BRIGHTNESS_OVERRIDE_ID = resolve(net.minecraft.world.entity.Display.class, "DATA_BRIGHTNESS_OVERRIDE_ID");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Float> DATA_VIEW_RANGE_ID = resolve(net.minecraft.world.entity.Display.class, "DATA_VIEW_RANGE_ID");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Float> DATA_SHADOW_RADIUS_ID = resolve(net.minecraft.world.entity.Display.class, "DATA_SHADOW_RADIUS_ID");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Float> DATA_SHADOW_STRENGTH_ID = resolve(net.minecraft.world.entity.Display.class, "DATA_SHADOW_STRENGTH_ID");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Float> DATA_WIDTH_ID = resolve(net.minecraft.world.entity.Display.class, "DATA_WIDTH_ID");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Float> DATA_HEIGHT_ID = resolve(net.minecraft.world.entity.Display.class, "DATA_HEIGHT_ID");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Integer> DATA_GLOW_COLOR_OVERRIDE_ID = resolve(net.minecraft.world.entity.Display.class, "DATA_GLOW_COLOR_OVERRIDE_ID");
    }


    public static class BlockDisplay extends Display {
        public static final net.minecraft.network.syncher.EntityDataAccessor<net.minecraft.world.level.block.state.BlockState> DATA_BLOCK_STATE_ID = resolve(net.minecraft.world.entity.Display.BlockDisplay.class, "DATA_BLOCK_STATE_ID");
    }

    public static class ItemDisplay extends Display {
        public static final net.minecraft.network.syncher.EntityDataAccessor<net.minecraft.world.item.ItemStack> DATA_ITEM_STACK_ID = resolve(net.minecraft.world.entity.Display.ItemDisplay.class, "DATA_ITEM_STACK_ID");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Byte> DATA_ITEM_DISPLAY_ID = resolve(net.minecraft.world.entity.Display.ItemDisplay.class, "DATA_ITEM_DISPLAY_ID");
    }

    public static class TextDisplay extends Display {
        public static final net.minecraft.network.syncher.EntityDataAccessor<net.minecraft.network.chat.Component> DATA_TEXT_ID = resolve(net.minecraft.world.entity.Display.TextDisplay.class, "DATA_TEXT_ID");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Integer> DATA_LINE_WIDTH_ID = resolve(net.minecraft.world.entity.Display.TextDisplay.class, "DATA_LINE_WIDTH_ID");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Integer> DATA_BACKGROUND_COLOR_ID = resolve(net.minecraft.world.entity.Display.TextDisplay.class, "DATA_BACKGROUND_COLOR_ID");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Byte> DATA_TEXT_OPACITY_ID = resolve(net.minecraft.world.entity.Display.TextDisplay.class, "DATA_TEXT_OPACITY_ID");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Byte> DATA_STYLE_FLAGS_ID = resolve(net.minecraft.world.entity.Display.TextDisplay.class, "DATA_STYLE_FLAGS_ID");
    }

    public static class ExperienceOrb extends Entity {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Integer> DATA_VALUE = resolve(net.minecraft.world.entity.ExperienceOrb.class, "DATA_VALUE");
    }

    public static class Interaction extends Entity {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Float> DATA_WIDTH_ID = resolve(net.minecraft.world.entity.Interaction.class, "DATA_WIDTH_ID");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Float> DATA_HEIGHT_ID = resolve(net.minecraft.world.entity.Interaction.class, "DATA_HEIGHT_ID");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Boolean> DATA_RESPONSE_ID = resolve(net.minecraft.world.entity.Interaction.class, "DATA_RESPONSE_ID");
    }

    public static class LivingEntity extends Entity {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Byte> DATA_LIVING_ENTITY_FLAGS = resolve(net.minecraft.world.entity.LivingEntity.class, "DATA_LIVING_ENTITY_FLAGS");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Float> DATA_HEALTH_ID = resolve(net.minecraft.world.entity.LivingEntity.class, "DATA_HEALTH_ID");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.util.List<net.minecraft.core.particles.ParticleOptions>> DATA_EFFECT_PARTICLES = resolve(net.minecraft.world.entity.LivingEntity.class, "DATA_EFFECT_PARTICLES");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Boolean> DATA_EFFECT_AMBIENCE_ID = resolve(net.minecraft.world.entity.LivingEntity.class, "DATA_EFFECT_AMBIENCE_ID");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Integer> DATA_ARROW_COUNT_ID = resolve(net.minecraft.world.entity.LivingEntity.class, "DATA_ARROW_COUNT_ID");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Integer> DATA_STINGER_COUNT_ID = resolve(net.minecraft.world.entity.LivingEntity.class, "DATA_STINGER_COUNT_ID");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.util.Optional<net.minecraft.core.BlockPos>> SLEEPING_POS_ID = resolve(net.minecraft.world.entity.LivingEntity.class, "SLEEPING_POS_ID");
    }


    public static class Avatar extends LivingEntity {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Byte> DATA_PLAYER_MAIN_HAND = resolve(net.minecraft.world.entity.Avatar.class, "DATA_PLAYER_MAIN_HAND");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Byte> DATA_PLAYER_MODE_CUSTOMISATION = resolve(net.minecraft.world.entity.Avatar.class, "DATA_PLAYER_MODE_CUSTOMISATION");
    }


    public static class Mannequin extends Avatar {
        public static final net.minecraft.network.syncher.EntityDataAccessor<net.minecraft.world.item.component.ResolvableProfile> DATA_PROFILE = resolve(net.minecraft.world.entity.decoration.Mannequin.class, "DATA_PROFILE");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Boolean> DATA_IMMOVABLE = resolve(net.minecraft.world.entity.decoration.Mannequin.class, "DATA_IMMOVABLE");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.util.Optional<net.minecraft.network.chat.Component>> DATA_DESCRIPTION = resolve(net.minecraft.world.entity.decoration.Mannequin.class, "DATA_DESCRIPTION");
    }

    public static class Player extends Avatar {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Float> DATA_PLAYER_ABSORPTION_ID = resolve(net.minecraft.world.entity.player.Player.class, "DATA_PLAYER_ABSORPTION_ID");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Integer> DATA_SCORE_ID = resolve(net.minecraft.world.entity.player.Player.class, "DATA_SCORE_ID");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.util.OptionalInt> DATA_SHOULDER_PARROT_LEFT = resolve(net.minecraft.world.entity.player.Player.class, "DATA_SHOULDER_PARROT_LEFT");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.util.OptionalInt> DATA_SHOULDER_PARROT_RIGHT = resolve(net.minecraft.world.entity.player.Player.class, "DATA_SHOULDER_PARROT_RIGHT");
    }

    public static class Mob extends LivingEntity {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Byte> DATA_MOB_FLAGS_ID = resolve(net.minecraft.world.entity.Mob.class, "DATA_MOB_FLAGS_ID");
    }


    public static class AgeableMob extends Mob {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Boolean> DATA_BABY_ID = resolve(net.minecraft.world.entity.AgeableMob.class, "DATA_BABY_ID");
    }


    public static class GlowSquid extends AgeableMob {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Integer> DATA_DARK_TICKS_REMAINING = resolve(net.minecraft.world.entity.GlowSquid.class, "DATA_DARK_TICKS_REMAINING");
    }

    public static class TamableAnimal extends AgeableMob {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Byte> DATA_FLAGS_ID = resolve(net.minecraft.world.entity.TamableAnimal.class, "DATA_FLAGS_ID");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.util.Optional<net.minecraft.world.entity.EntityReference<net.minecraft.world.entity.LivingEntity>>> DATA_OWNERUUID_ID = resolve(net.minecraft.world.entity.TamableAnimal.class, "DATA_OWNERUUID_ID");
    }


    public static class Cat extends TamableAnimal {
        public static final net.minecraft.network.syncher.EntityDataAccessor<net.minecraft.core.Holder<net.minecraft.world.entity.animal.CatVariant>> DATA_VARIANT_ID = resolve(net.minecraft.world.entity.animal.Cat.class, "DATA_VARIANT_ID");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Boolean> IS_LYING = resolve(net.minecraft.world.entity.animal.Cat.class, "IS_LYING");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Boolean> RELAX_STATE_ONE = resolve(net.minecraft.world.entity.animal.Cat.class, "RELAX_STATE_ONE");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Integer> DATA_COLLAR_COLOR = resolve(net.minecraft.world.entity.animal.Cat.class, "DATA_COLLAR_COLOR");
    }

    public static class Parrot extends TamableAnimal {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Integer> DATA_VARIANT_ID = resolve(net.minecraft.world.entity.animal.Parrot.class, "DATA_VARIANT_ID");
    }

    public static class Wolf extends TamableAnimal {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Boolean> DATA_INTERESTED_ID = resolve(net.minecraft.world.entity.animal.wolf.Wolf.class, "DATA_INTERESTED_ID");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Integer> DATA_COLLAR_COLOR = resolve(net.minecraft.world.entity.animal.wolf.Wolf.class, "DATA_COLLAR_COLOR");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Integer> DATA_REMAINING_ANGER_TIME = resolve(net.minecraft.world.entity.animal.wolf.Wolf.class, "DATA_REMAINING_ANGER_TIME");
        public static final net.minecraft.network.syncher.EntityDataAccessor<net.minecraft.core.Holder<net.minecraft.world.entity.animal.wolf.WolfVariant>> DATA_VARIANT_ID = resolve(net.minecraft.world.entity.animal.wolf.Wolf.class, "DATA_VARIANT_ID");
        public static final net.minecraft.network.syncher.EntityDataAccessor<net.minecraft.core.Holder<net.minecraft.world.entity.animal.wolf.WolfSoundVariant>> DATA_SOUND_VARIANT_ID = resolve(net.minecraft.world.entity.animal.wolf.Wolf.class, "DATA_SOUND_VARIANT_ID");
    }

    public static class Bee extends AgeableMob {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Byte> DATA_FLAGS_ID = resolve(net.minecraft.world.entity.animal.Bee.class, "DATA_FLAGS_ID");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Integer> DATA_REMAINING_ANGER_TIME = resolve(net.minecraft.world.entity.animal.Bee.class, "DATA_REMAINING_ANGER_TIME");
    }

    public static class Chicken extends AgeableMob {
        public static final net.minecraft.network.syncher.EntityDataAccessor<net.minecraft.core.Holder<net.minecraft.world.entity.animal.ChickenVariant>> DATA_VARIANT_ID = resolve(net.minecraft.world.entity.animal.Chicken.class, "DATA_VARIANT_ID");
    }

    public static class Cow extends AgeableMob {
        public static final net.minecraft.network.syncher.EntityDataAccessor<net.minecraft.core.Holder<net.minecraft.world.entity.animal.CowVariant>> DATA_VARIANT_ID = resolve(net.minecraft.world.entity.animal.Cow.class, "DATA_VARIANT_ID");
    }

    public static class Dolphin extends AgeableMob {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Boolean> GOT_FISH = resolve(net.minecraft.world.entity.animal.Dolphin.class, "GOT_FISH");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Integer> MOISTNESS_LEVEL = resolve(net.minecraft.world.entity.animal.Dolphin.class, "MOISTNESS_LEVEL");
    }

    public static class Fox extends AgeableMob {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Integer> DATA_TYPE_ID = resolve(net.minecraft.world.entity.animal.Fox.class, "DATA_TYPE_ID");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Byte> DATA_FLAGS_ID = resolve(net.minecraft.world.entity.animal.Fox.class, "DATA_FLAGS_ID");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.util.Optional<net.minecraft.world.entity.EntityReference<net.minecraft.world.entity.LivingEntity>>> DATA_TRUSTED_ID_0 = resolve(net.minecraft.world.entity.animal.Fox.class, "DATA_TRUSTED_ID_0");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.util.Optional<net.minecraft.world.entity.EntityReference<net.minecraft.world.entity.LivingEntity>>> DATA_TRUSTED_ID_1 = resolve(net.minecraft.world.entity.animal.Fox.class, "DATA_TRUSTED_ID_1");
    }

    public static class HappyGhast extends AgeableMob {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Boolean> IS_LEASH_HOLDER = resolve(net.minecraft.world.entity.animal.HappyGhast.class, "IS_LEASH_HOLDER");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Boolean> STAYS_STILL = resolve(net.minecraft.world.entity.animal.HappyGhast.class, "STAYS_STILL");
    }

    public static class MushroomCow extends AgeableMob {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Integer> DATA_TYPE = resolve(net.minecraft.world.entity.animal.MushroomCow.class, "DATA_TYPE");
    }

    public static class Ocelot extends AgeableMob {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Boolean> DATA_TRUSTING = resolve(net.minecraft.world.entity.animal.Ocelot.class, "DATA_TRUSTING");
    }

    public static class Panda extends AgeableMob {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Integer> UNHAPPY_COUNTER = resolve(net.minecraft.world.entity.animal.Panda.class, "UNHAPPY_COUNTER");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Integer> SNEEZE_COUNTER = resolve(net.minecraft.world.entity.animal.Panda.class, "SNEEZE_COUNTER");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Integer> EAT_COUNTER = resolve(net.minecraft.world.entity.animal.Panda.class, "EAT_COUNTER");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Byte> MAIN_GENE_ID = resolve(net.minecraft.world.entity.animal.Panda.class, "MAIN_GENE_ID");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Byte> HIDDEN_GENE_ID = resolve(net.minecraft.world.entity.animal.Panda.class, "HIDDEN_GENE_ID");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Byte> DATA_ID_FLAGS = resolve(net.minecraft.world.entity.animal.Panda.class, "DATA_ID_FLAGS");
    }

    public static class Pig extends AgeableMob {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Integer> DATA_BOOST_TIME = resolve(net.minecraft.world.entity.animal.Pig.class, "DATA_BOOST_TIME");
        public static final net.minecraft.network.syncher.EntityDataAccessor<net.minecraft.core.Holder<net.minecraft.world.entity.animal.PigVariant>> DATA_VARIANT_ID = resolve(net.minecraft.world.entity.animal.Pig.class, "DATA_VARIANT_ID");
    }

    public static class PolarBear extends AgeableMob {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Boolean> DATA_STANDING_ID = resolve(net.minecraft.world.entity.animal.PolarBear.class, "DATA_STANDING_ID");
    }

    public static class Rabbit extends AgeableMob {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Integer> DATA_TYPE_ID = resolve(net.minecraft.world.entity.animal.Rabbit.class, "DATA_TYPE_ID");
    }

    public static class Turtle extends AgeableMob {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Boolean> HAS_EGG = resolve(net.minecraft.world.entity.animal.Turtle.class, "HAS_EGG");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Boolean> LAYING_EGG = resolve(net.minecraft.world.entity.animal.Turtle.class, "LAYING_EGG");
    }

    public static class Armadillo extends AgeableMob {
        public static final net.minecraft.network.syncher.EntityDataAccessor<net.minecraft.world.entity.animal.armadillo.Armadillo.ArmadilloState> ARMADILLO_STATE = resolve(net.minecraft.world.entity.animal.armadillo.Armadillo.class, "ARMADILLO_STATE");
    }

    public static class Axolotl extends AgeableMob {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Integer> DATA_VARIANT = resolve(net.minecraft.world.entity.animal.axolotl.Axolotl.class, "DATA_VARIANT");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Boolean> DATA_PLAYING_DEAD = resolve(net.minecraft.world.entity.animal.axolotl.Axolotl.class, "DATA_PLAYING_DEAD");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Boolean> FROM_BUCKET = resolve(net.minecraft.world.entity.animal.axolotl.Axolotl.class, "FROM_BUCKET");
    }

    public static class Frog extends AgeableMob {
        public static final net.minecraft.network.syncher.EntityDataAccessor<net.minecraft.core.Holder<net.minecraft.world.entity.animal.frog.FrogVariant>> DATA_VARIANT_ID = resolve(net.minecraft.world.entity.animal.frog.Frog.class, "DATA_VARIANT_ID");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.util.OptionalInt> DATA_TONGUE_TARGET_ID = resolve(net.minecraft.world.entity.animal.frog.Frog.class, "DATA_TONGUE_TARGET_ID");
    }

    public static class Goat extends AgeableMob {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Boolean> DATA_IS_SCREAMING_GOAT = resolve(net.minecraft.world.entity.animal.goat.Goat.class, "DATA_IS_SCREAMING_GOAT");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Boolean> DATA_HAS_LEFT_HORN = resolve(net.minecraft.world.entity.animal.goat.Goat.class, "DATA_HAS_LEFT_HORN");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Boolean> DATA_HAS_RIGHT_HORN = resolve(net.minecraft.world.entity.animal.goat.Goat.class, "DATA_HAS_RIGHT_HORN");
    }

    public static class AbstractHorse extends AgeableMob {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Byte> DATA_ID_FLAGS = resolve(net.minecraft.world.entity.animal.horse.AbstractHorse.class, "DATA_ID_FLAGS");
    }


    public static class Camel extends AbstractHorse {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Boolean> DASH = resolve(net.minecraft.world.entity.animal.camel.Camel.class, "DASH");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Long> LAST_POSE_CHANGE_TICK = resolve(net.minecraft.world.entity.animal.camel.Camel.class, "LAST_POSE_CHANGE_TICK");
    }

    public static class AbstractChestedHorse extends AbstractHorse {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Boolean> DATA_ID_CHEST = resolve(net.minecraft.world.entity.animal.horse.AbstractChestedHorse.class, "DATA_ID_CHEST");
    }


    public static class Llama extends AbstractChestedHorse {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Integer> DATA_STRENGTH_ID = resolve(net.minecraft.world.entity.animal.horse.Llama.class, "DATA_STRENGTH_ID");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Integer> DATA_VARIANT_ID = resolve(net.minecraft.world.entity.animal.horse.Llama.class, "DATA_VARIANT_ID");
    }

    public static class Horse extends AbstractHorse {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Integer> DATA_ID_TYPE_VARIANT = resolve(net.minecraft.world.entity.animal.horse.Horse.class, "DATA_ID_TYPE_VARIANT");
    }

    public static class Sheep extends AgeableMob {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Byte> DATA_WOOL_ID = resolve(net.minecraft.world.entity.animal.sheep.Sheep.class, "DATA_WOOL_ID");
    }

    public static class Sniffer extends AgeableMob {
        public static final net.minecraft.network.syncher.EntityDataAccessor<net.minecraft.world.entity.animal.sniffer.Sniffer.State> DATA_STATE = resolve(net.minecraft.world.entity.animal.sniffer.Sniffer.class, "DATA_STATE");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Integer> DATA_DROP_SEED_AT_TICK = resolve(net.minecraft.world.entity.animal.sniffer.Sniffer.class, "DATA_DROP_SEED_AT_TICK");
    }

    public static class Strider extends AgeableMob {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Integer> DATA_BOOST_TIME = resolve(net.minecraft.world.entity.monster.Strider.class, "DATA_BOOST_TIME");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Boolean> DATA_SUFFOCATING = resolve(net.minecraft.world.entity.monster.Strider.class, "DATA_SUFFOCATING");
    }

    public static class Hoglin extends AgeableMob {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Boolean> DATA_IMMUNE_TO_ZOMBIFICATION = resolve(net.minecraft.world.entity.monster.hoglin.Hoglin.class, "DATA_IMMUNE_TO_ZOMBIFICATION");
    }

    public static class AbstractVillager extends AgeableMob {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Integer> DATA_UNHAPPY_COUNTER = resolve(net.minecraft.world.entity.npc.AbstractVillager.class, "DATA_UNHAPPY_COUNTER");
    }


    public static class Villager extends AbstractVillager {
        public static final net.minecraft.network.syncher.EntityDataAccessor<net.minecraft.world.entity.npc.VillagerData> DATA_VILLAGER_DATA = resolve(net.minecraft.world.entity.npc.Villager.class, "DATA_VILLAGER_DATA");
    }

    public static class Bat extends Mob {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Byte> DATA_ID_FLAGS = resolve(net.minecraft.world.entity.ambient.Bat.class, "DATA_ID_FLAGS");
    }

    public static class AbstractFish extends Mob {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Boolean> FROM_BUCKET = resolve(net.minecraft.world.entity.animal.AbstractFish.class, "FROM_BUCKET");
    }


    public static class Pufferfish extends AbstractFish {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Integer> PUFF_STATE = resolve(net.minecraft.world.entity.animal.Pufferfish.class, "PUFF_STATE");
    }

    public static class Salmon extends AbstractFish {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Integer> DATA_TYPE = resolve(net.minecraft.world.entity.animal.Salmon.class, "DATA_TYPE");
    }

    public static class TropicalFish extends AbstractFish {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Integer> DATA_ID_TYPE_VARIANT = resolve(net.minecraft.world.entity.animal.TropicalFish.class, "DATA_ID_TYPE_VARIANT");
    }

    public static class IronGolem extends Mob {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Byte> DATA_FLAGS_ID = resolve(net.minecraft.world.entity.animal.IronGolem.class, "DATA_FLAGS_ID");
    }

    public static class SnowGolem extends Mob {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Byte> DATA_PUMPKIN_ID = resolve(net.minecraft.world.entity.animal.SnowGolem.class, "DATA_PUMPKIN_ID");
    }

    public static class Allay extends Mob {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Boolean> DATA_DANCING = resolve(net.minecraft.world.entity.animal.allay.Allay.class, "DATA_DANCING");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Boolean> DATA_CAN_DUPLICATE = resolve(net.minecraft.world.entity.animal.allay.Allay.class, "DATA_CAN_DUPLICATE");
    }

    public static class CopperGolem extends Mob {
        public static final net.minecraft.network.syncher.EntityDataAccessor<net.minecraft.world.level.block.WeatheringCopper.WeatherState> DATA_WEATHER_STATE = resolve(net.minecraft.world.entity.animal.coppergolem.CopperGolem.class, "DATA_WEATHER_STATE");
        public static final net.minecraft.network.syncher.EntityDataAccessor<net.minecraft.world.entity.animal.coppergolem.CopperGolemState> COPPER_GOLEM_STATE = resolve(net.minecraft.world.entity.animal.coppergolem.CopperGolem.class, "COPPER_GOLEM_STATE");
    }

    public static class EnderDragon extends Mob {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Integer> DATA_PHASE = resolve(net.minecraft.world.entity.boss.enderdragon.EnderDragon.class, "DATA_PHASE");
    }

    public static class WitherBoss extends Mob {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Integer> DATA_TARGET_A = resolve(net.minecraft.world.entity.boss.wither.WitherBoss.class, "DATA_TARGET_A");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Integer> DATA_TARGET_B = resolve(net.minecraft.world.entity.boss.wither.WitherBoss.class, "DATA_TARGET_B");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Integer> DATA_TARGET_C = resolve(net.minecraft.world.entity.boss.wither.WitherBoss.class, "DATA_TARGET_C");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Integer> DATA_ID_INV = resolve(net.minecraft.world.entity.boss.wither.WitherBoss.class, "DATA_ID_INV");
    }

    public static class Blaze extends Mob {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Byte> DATA_FLAGS_ID = resolve(net.minecraft.world.entity.monster.Blaze.class, "DATA_FLAGS_ID");
    }

    public static class Bogged extends Mob {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Boolean> DATA_SHEARED = resolve(net.minecraft.world.entity.monster.Bogged.class, "DATA_SHEARED");
    }

    public static class Creeper extends Mob {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Integer> DATA_SWELL_DIR = resolve(net.minecraft.world.entity.monster.Creeper.class, "DATA_SWELL_DIR");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Boolean> DATA_IS_POWERED = resolve(net.minecraft.world.entity.monster.Creeper.class, "DATA_IS_POWERED");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Boolean> DATA_IS_IGNITED = resolve(net.minecraft.world.entity.monster.Creeper.class, "DATA_IS_IGNITED");
    }

    public static class EnderMan extends Mob {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.util.Optional<net.minecraft.world.level.block.state.BlockState>> DATA_CARRY_STATE = resolve(net.minecraft.world.entity.monster.EnderMan.class, "DATA_CARRY_STATE");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Boolean> DATA_CREEPY = resolve(net.minecraft.world.entity.monster.EnderMan.class, "DATA_CREEPY");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Boolean> DATA_STARED_AT = resolve(net.minecraft.world.entity.monster.EnderMan.class, "DATA_STARED_AT");
    }

    public static class Ghast extends Mob {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Boolean> DATA_IS_CHARGING = resolve(net.minecraft.world.entity.monster.Ghast.class, "DATA_IS_CHARGING");
    }

    public static class Guardian extends Mob {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Boolean> DATA_ID_MOVING = resolve(net.minecraft.world.entity.monster.Guardian.class, "DATA_ID_MOVING");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Integer> DATA_ID_ATTACK_TARGET = resolve(net.minecraft.world.entity.monster.Guardian.class, "DATA_ID_ATTACK_TARGET");
    }

    public static class Phantom extends Mob {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Integer> ID_SIZE = resolve(net.minecraft.world.entity.monster.Phantom.class, "ID_SIZE");
    }

    public static class Shulker extends Mob {
        public static final net.minecraft.network.syncher.EntityDataAccessor<net.minecraft.core.Direction> DATA_ATTACH_FACE_ID = resolve(net.minecraft.world.entity.monster.Shulker.class, "DATA_ATTACH_FACE_ID");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Byte> DATA_PEEK_ID = resolve(net.minecraft.world.entity.monster.Shulker.class, "DATA_PEEK_ID");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Byte> DATA_COLOR_ID = resolve(net.minecraft.world.entity.monster.Shulker.class, "DATA_COLOR_ID");
    }

    public static class Skeleton extends Mob {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Boolean> DATA_STRAY_CONVERSION_ID = resolve(net.minecraft.world.entity.monster.Skeleton.class, "DATA_STRAY_CONVERSION_ID");
    }

    public static class Slime extends Mob {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Integer> ID_SIZE = resolve(net.minecraft.world.entity.monster.Slime.class, "ID_SIZE");
    }

    public static class Spider extends Mob {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Byte> DATA_FLAGS_ID = resolve(net.minecraft.world.entity.monster.Spider.class, "DATA_FLAGS_ID");
    }

    public static class Vex extends Mob {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Byte> DATA_FLAGS_ID = resolve(net.minecraft.world.entity.monster.Vex.class, "DATA_FLAGS_ID");
    }

    public static class Zoglin extends Mob {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Boolean> DATA_BABY_ID = resolve(net.minecraft.world.entity.monster.Zoglin.class, "DATA_BABY_ID");
    }

    public static class Zombie extends Mob {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Boolean> DATA_BABY_ID = resolve(net.minecraft.world.entity.monster.Zombie.class, "DATA_BABY_ID");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Integer> DATA_SPECIAL_TYPE_ID = resolve(net.minecraft.world.entity.monster.Zombie.class, "DATA_SPECIAL_TYPE_ID");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Boolean> DATA_DROWNED_CONVERSION_ID = resolve(net.minecraft.world.entity.monster.Zombie.class, "DATA_DROWNED_CONVERSION_ID");
    }


    public static class ZombieVillager extends Zombie {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Boolean> DATA_CONVERTING_ID = resolve(net.minecraft.world.entity.monster.ZombieVillager.class, "DATA_CONVERTING_ID");
        public static final net.minecraft.network.syncher.EntityDataAccessor<net.minecraft.world.entity.npc.VillagerData> DATA_VILLAGER_DATA = resolve(net.minecraft.world.entity.monster.ZombieVillager.class, "DATA_VILLAGER_DATA");
    }

    public static class Creaking extends Mob {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Boolean> CAN_MOVE = resolve(net.minecraft.world.entity.monster.creaking.Creaking.class, "CAN_MOVE");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Boolean> IS_ACTIVE = resolve(net.minecraft.world.entity.monster.creaking.Creaking.class, "IS_ACTIVE");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Boolean> IS_TEARING_DOWN = resolve(net.minecraft.world.entity.monster.creaking.Creaking.class, "IS_TEARING_DOWN");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.util.Optional<net.minecraft.core.BlockPos>> HOME_POS = resolve(net.minecraft.world.entity.monster.creaking.Creaking.class, "HOME_POS");
    }

    public static class AbstractPiglin extends Mob {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Boolean> DATA_IMMUNE_TO_ZOMBIFICATION = resolve(net.minecraft.world.entity.monster.piglin.AbstractPiglin.class, "DATA_IMMUNE_TO_ZOMBIFICATION");
    }


    public static class Piglin extends AbstractPiglin {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Boolean> DATA_BABY_ID = resolve(net.minecraft.world.entity.monster.piglin.Piglin.class, "DATA_BABY_ID");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Boolean> DATA_IS_CHARGING_CROSSBOW = resolve(net.minecraft.world.entity.monster.piglin.Piglin.class, "DATA_IS_CHARGING_CROSSBOW");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Boolean> DATA_IS_DANCING = resolve(net.minecraft.world.entity.monster.piglin.Piglin.class, "DATA_IS_DANCING");
    }

    public static class Warden extends Mob {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Integer> CLIENT_ANGER_LEVEL = resolve(net.minecraft.world.entity.monster.warden.Warden.class, "CLIENT_ANGER_LEVEL");
    }

    public static class Raider extends Mob {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Boolean> IS_CELEBRATING = resolve(net.minecraft.world.entity.raid.Raider.class, "IS_CELEBRATING");
    }


    public static class Pillager extends Raider {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Boolean> IS_CHARGING_CROSSBOW = resolve(net.minecraft.world.entity.monster.Pillager.class, "IS_CHARGING_CROSSBOW");
    }

    public static class SpellcasterIllager extends Raider {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Byte> DATA_SPELL_CASTING_ID = resolve(net.minecraft.world.entity.monster.SpellcasterIllager.class, "DATA_SPELL_CASTING_ID");
    }

    public static class Witch extends Raider {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Boolean> DATA_USING_ITEM = resolve(net.minecraft.world.entity.monster.Witch.class, "DATA_USING_ITEM");
    }

    public static class ArmorStand extends LivingEntity {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Byte> DATA_CLIENT_FLAGS = resolve(net.minecraft.world.entity.decoration.ArmorStand.class, "DATA_CLIENT_FLAGS");
        public static final net.minecraft.network.syncher.EntityDataAccessor<net.minecraft.core.Rotations> DATA_HEAD_POSE = resolve(net.minecraft.world.entity.decoration.ArmorStand.class, "DATA_HEAD_POSE");
        public static final net.minecraft.network.syncher.EntityDataAccessor<net.minecraft.core.Rotations> DATA_BODY_POSE = resolve(net.minecraft.world.entity.decoration.ArmorStand.class, "DATA_BODY_POSE");
        public static final net.minecraft.network.syncher.EntityDataAccessor<net.minecraft.core.Rotations> DATA_LEFT_ARM_POSE = resolve(net.minecraft.world.entity.decoration.ArmorStand.class, "DATA_LEFT_ARM_POSE");
        public static final net.minecraft.network.syncher.EntityDataAccessor<net.minecraft.core.Rotations> DATA_RIGHT_ARM_POSE = resolve(net.minecraft.world.entity.decoration.ArmorStand.class, "DATA_RIGHT_ARM_POSE");
        public static final net.minecraft.network.syncher.EntityDataAccessor<net.minecraft.core.Rotations> DATA_LEFT_LEG_POSE = resolve(net.minecraft.world.entity.decoration.ArmorStand.class, "DATA_LEFT_LEG_POSE");
        public static final net.minecraft.network.syncher.EntityDataAccessor<net.minecraft.core.Rotations> DATA_RIGHT_LEG_POSE = resolve(net.minecraft.world.entity.decoration.ArmorStand.class, "DATA_RIGHT_LEG_POSE");
    }

    public static class OminousItemSpawner extends Entity {
        public static final net.minecraft.network.syncher.EntityDataAccessor<net.minecraft.world.item.ItemStack> DATA_ITEM = resolve(net.minecraft.world.entity.OminousItemSpawner.class, "DATA_ITEM");
    }

    public static class EndCrystal extends Entity {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.util.Optional<net.minecraft.core.BlockPos>> DATA_BEAM_TARGET = resolve(net.minecraft.world.entity.boss.enderdragon.EndCrystal.class, "DATA_BEAM_TARGET");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Boolean> DATA_SHOW_BOTTOM = resolve(net.minecraft.world.entity.boss.enderdragon.EndCrystal.class, "DATA_SHOW_BOTTOM");
    }

    public static class HangingEntity extends Entity {
        public static final net.minecraft.network.syncher.EntityDataAccessor<net.minecraft.core.Direction> DATA_DIRECTION = resolve(net.minecraft.world.entity.decoration.HangingEntity.class, "DATA_DIRECTION");
    }


    public static class ItemFrame extends HangingEntity {
        public static final net.minecraft.network.syncher.EntityDataAccessor<net.minecraft.world.item.ItemStack> DATA_ITEM = resolve(net.minecraft.world.entity.decoration.ItemFrame.class, "DATA_ITEM");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Integer> DATA_ROTATION = resolve(net.minecraft.world.entity.decoration.ItemFrame.class, "DATA_ROTATION");
    }

    public static class Painting extends HangingEntity {
        public static final net.minecraft.network.syncher.EntityDataAccessor<net.minecraft.core.Holder<net.minecraft.world.entity.decoration.PaintingVariant>> DATA_PAINTING_VARIANT_ID = resolve(net.minecraft.world.entity.decoration.Painting.class, "DATA_PAINTING_VARIANT_ID");
    }

    public static class FallingBlockEntity extends Entity {
        public static final net.minecraft.network.syncher.EntityDataAccessor<net.minecraft.core.BlockPos> DATA_START_POS = resolve(net.minecraft.world.entity.item.FallingBlockEntity.class, "DATA_START_POS");
    }

    public static class ItemEntity extends Entity {
        public static final net.minecraft.network.syncher.EntityDataAccessor<net.minecraft.world.item.ItemStack> DATA_ITEM = resolve(net.minecraft.world.entity.item.ItemEntity.class, "DATA_ITEM");
    }

    public static class PrimedTnt extends Entity {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Integer> DATA_FUSE_ID = resolve(net.minecraft.world.entity.item.PrimedTnt.class, "DATA_FUSE_ID");
        public static final net.minecraft.network.syncher.EntityDataAccessor<net.minecraft.world.level.block.state.BlockState> DATA_BLOCK_STATE_ID = resolve(net.minecraft.world.entity.item.PrimedTnt.class, "DATA_BLOCK_STATE_ID");
    }

    public static class AbstractArrow extends Entity {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Byte> ID_FLAGS = resolve(net.minecraft.world.entity.projectile.AbstractArrow.class, "ID_FLAGS");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Byte> PIERCE_LEVEL = resolve(net.minecraft.world.entity.projectile.AbstractArrow.class, "PIERCE_LEVEL");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Boolean> IN_GROUND = resolve(net.minecraft.world.entity.projectile.AbstractArrow.class, "IN_GROUND");
    }


    public static class Arrow extends AbstractArrow {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Integer> ID_EFFECT_COLOR = resolve(net.minecraft.world.entity.projectile.Arrow.class, "ID_EFFECT_COLOR");
    }

    public static class ThrownTrident extends AbstractArrow {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Byte> ID_LOYALTY = resolve(net.minecraft.world.entity.projectile.ThrownTrident.class, "ID_LOYALTY");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Boolean> ID_FOIL = resolve(net.minecraft.world.entity.projectile.ThrownTrident.class, "ID_FOIL");
    }

    public static class EyeOfEnder extends Entity {
        public static final net.minecraft.network.syncher.EntityDataAccessor<net.minecraft.world.item.ItemStack> DATA_ITEM_STACK = resolve(net.minecraft.world.entity.projectile.EyeOfEnder.class, "DATA_ITEM_STACK");
    }

    public static class Fireball extends Entity {
        public static final net.minecraft.network.syncher.EntityDataAccessor<net.minecraft.world.item.ItemStack> DATA_ITEM_STACK = resolve(net.minecraft.world.entity.projectile.Fireball.class, "DATA_ITEM_STACK");
    }

    public static class FireworkRocketEntity extends Entity {
        public static final net.minecraft.network.syncher.EntityDataAccessor<net.minecraft.world.item.ItemStack> DATA_ID_FIREWORKS_ITEM = resolve(net.minecraft.world.entity.projectile.FireworkRocketEntity.class, "DATA_ID_FIREWORKS_ITEM");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.util.OptionalInt> DATA_ATTACHED_TO_TARGET = resolve(net.minecraft.world.entity.projectile.FireworkRocketEntity.class, "DATA_ATTACHED_TO_TARGET");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Boolean> DATA_SHOT_AT_ANGLE = resolve(net.minecraft.world.entity.projectile.FireworkRocketEntity.class, "DATA_SHOT_AT_ANGLE");
    }

    public static class FishingHook extends Entity {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Integer> DATA_HOOKED_ENTITY = resolve(net.minecraft.world.entity.projectile.FishingHook.class, "DATA_HOOKED_ENTITY");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Boolean> DATA_BITING = resolve(net.minecraft.world.entity.projectile.FishingHook.class, "DATA_BITING");
    }

    public static class ThrowableItemProjectile extends Entity {
        public static final net.minecraft.network.syncher.EntityDataAccessor<net.minecraft.world.item.ItemStack> DATA_ITEM_STACK = resolve(net.minecraft.world.entity.projectile.ThrowableItemProjectile.class, "DATA_ITEM_STACK");
    }

    public static class WitherSkull extends Entity {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Boolean> DATA_DANGEROUS = resolve(net.minecraft.world.entity.projectile.WitherSkull.class, "DATA_DANGEROUS");
    }

    public static class VehicleEntity extends Entity {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Integer> DATA_ID_HURT = resolve(net.minecraft.world.entity.vehicle.VehicleEntity.class, "DATA_ID_HURT");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Integer> DATA_ID_HURTDIR = resolve(net.minecraft.world.entity.vehicle.VehicleEntity.class, "DATA_ID_HURTDIR");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Float> DATA_ID_DAMAGE = resolve(net.minecraft.world.entity.vehicle.VehicleEntity.class, "DATA_ID_DAMAGE");
    }


    public static class AbstractBoat extends VehicleEntity {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Boolean> DATA_ID_PADDLE_LEFT = resolve(net.minecraft.world.entity.vehicle.AbstractBoat.class, "DATA_ID_PADDLE_LEFT");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Boolean> DATA_ID_PADDLE_RIGHT = resolve(net.minecraft.world.entity.vehicle.AbstractBoat.class, "DATA_ID_PADDLE_RIGHT");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Integer> DATA_ID_BUBBLE_TIME = resolve(net.minecraft.world.entity.vehicle.AbstractBoat.class, "DATA_ID_BUBBLE_TIME");
    }

    public static class AbstractMinecart extends VehicleEntity {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.util.Optional<net.minecraft.world.level.block.state.BlockState>> DATA_ID_CUSTOM_DISPLAY_BLOCK = resolve(net.minecraft.world.entity.vehicle.AbstractMinecart.class, "DATA_ID_CUSTOM_DISPLAY_BLOCK");
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Integer> DATA_ID_DISPLAY_OFFSET = resolve(net.minecraft.world.entity.vehicle.AbstractMinecart.class, "DATA_ID_DISPLAY_OFFSET");
    }


    public static class MinecartCommandBlock extends AbstractMinecart {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.String> DATA_ID_COMMAND_NAME = resolve(net.minecraft.world.entity.vehicle.MinecartCommandBlock.class, "DATA_ID_COMMAND_NAME");
        public static final net.minecraft.network.syncher.EntityDataAccessor<net.minecraft.network.chat.Component> DATA_ID_LAST_OUTPUT = resolve(net.minecraft.world.entity.vehicle.MinecartCommandBlock.class, "DATA_ID_LAST_OUTPUT");
    }

    public static class MinecartFurnace extends AbstractMinecart {
        public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Boolean> DATA_ID_FUEL = resolve(net.minecraft.world.entity.vehicle.MinecartFurnace.class, "DATA_ID_FUEL");
    }

}
